---
# Credentials for AAP Controller
# Note: "GitHub PAT" SCM credential should be created manually before running this playbook
controller_credentials:
  - name: "OpenShift API Credential"
    description: "Credential for connecting to OpenShift cluster"
    organization: "{{ organization_name }}"
    credential_type: "OpenShift or Kubernetes API Bearer Token"
    inputs:
      host: "{{ openshift_api_url }}"
      bearer_token: "{{ openshift_api_token }}"
      verify_ssl: "{{ openshift_validate_certs }}"
