---
# Hosts for AAP Controller Inventories
controller_hosts:
  - name: "localhost"
    inventory: "OpenShift Cluster"
    variables:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3

  - name: "localhost"
    inventory: "Localhost"
    variables:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
